name: animate_do
description: Beautiful animations inspired by Animate.css for Flutter. Custom fork without debug prints.
version: 3.3.9
homepage: https://github.com/username/animate_do

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  # No assets needed